name: Publish Nuget

on:
  push:
    tags: [v*]

permissions:
  contents: read

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Package
      run: dotnet pack --configuration Release -o out
    - name: Publish
      run: dotnet nuget push out/*.nupkg -k ${NUGET_AUTH_TOKEN} -s https://api.nuget.org/v3/index.json  --skip-duplicate --no-symbols true
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
